### ISSUE TITLE
FileMgr mksubdir func

### ISSUE THREAD

**Issue by jselikof** [n6xej/RRStructureScannerSwift5#1]
In func `mksubdir` It looks like `subpath` should be checked for existence instead of `fullPath` since `exists` creates `fullPath`.  Actually, it looks like that pattern is repeated for func `filepath` as well.

**Comment by n6xej** [comment]
I think the problem is in "func exists( _ name: String) -> Bool" as it appends what is passed into it to self.basePath (~/Documents). There are 5 places self.exists() is called, and prior to everywhere it is called either a function is called that returns the input value appended to self.basePath or explicitly calls self.basePath.appendingPathComponent(input) prior to calling self.exists(). 

So can either remove the calls to develop the full path prior to calling self.exists(), or remove the call to "self.basePath.appendingPathComponent(name)"  and just passing the "name" parameter to FileManager.default.fileExists(atPath: name). Thanks for spotting that!

**Comment by n6xej** [comment]
Actually best just to remove the call to self.basePath.appendingPathComponent(name) and use the input value in the func self.exists().
Some of the functions that call self.exists() need the full path after calling self.exists().
